from fastapi import APIRouter, Depends, HTTPException, Response
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.db.models import Document, RiskReport, Clause
from app.services.report_generator import PDFReportGenerator

router = APIRouter()

@router.get("/report/{id}")
def generate_audit_report(
    id: str,
    db: Session = Depends(get_db)
):
    """
    Generates and downloads a compiled PDF legal audit report for document ID.
    """
    doc = db.query(Document).filter(Document.id == id).first()
    if not doc:
        # Generate sample PDF report if doc ID is fresh/demo
        sample_report = {
            "overallRisk": 78,
            "recommendation": "Proceed Carefully",
            "summary": "Sample Legal Risk Audit Report generated by CLARA AI engine.",
            "trustScore": 65,
            "privacyScore": 82,
            "financialRisk": 71,
            "complianceRisk": 64,
            "transparencyScore": 58,
            "hiddenClauses": [{"category": "Unilateral Amendments", "reason": "Terms can change without prior user consent."}]
        }
        pdf_bytes = PDFReportGenerator.generate_report_pdf(sample_report, "Terms & Conditions Audit")
        return Response(content=pdf_bytes, media_type="application/pdf", headers={"Content-Disposition": f"attachment; filename=CLARA_Report_{id}.pdf"})

    rep = db.query(RiskReport).filter(RiskReport.document_id == id).first()
    report_dict = {
        "overallRisk": rep.overall_risk if rep else 50,
        "recommendation": rep.recommendation if rep else "Proceed Carefully",
        "summary": rep.summary if rep else "Legal Audit Report",
        "trustScore": rep.trust_score if rep else 70,
        "privacyScore": rep.privacy_score if rep else 70,
        "financialRisk": rep.financial_risk if rep else 50,
        "complianceRisk": rep.compliance_risk if rep else 50,
        "transparencyScore": rep.transparency_score if rep else 70,
        "hiddenClauses": rep.hidden_clauses if rep else []
    }

    pdf_bytes = PDFReportGenerator.generate_report_pdf(report_dict, doc.title)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=CLARA_Audit_{id}.pdf"}
    )
